apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodeapp
  name: nodeapp-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodeapp
  type: ClusterIP